### ISSUE TITLE
Add Copenhagen Announcement Blog Post

### ISSUE THREAD

**Issue by mhils** [honeynet/honeynet.github.io#50]
...and make it sticky. Just needs to say that we're having a workshop again (yay!) and point to https://denmark2024.honeynet.org/. :)

**Comment by Sam-wiz** [comment]
Hello, 
I just want to ask: on which page should I add this? On a blog page or on the home page?

**Comment by hgascon** [comment]
Blog page

**Comment by hgascon** [comment]
And/or the home page if you are able to hack a fancy banner or announcement
