### ISSUE TITLE
GSoC homepage?

### ISSUE THREAD

**Issue by xandfury** [honeynet/honeynet.github.io#51]
Was thinking that we should have a general information gsoc page on the site with discord invite link and ideas. GSoC year pages should contain ideas for that year and results/reports. 

Thoughts? :-)

**Comment by hgascon** [comment]
Sounds good to me. Would you like to create a draft?

**Comment by Sam-wiz** [comment]
I am interested in it. I would like to add the template for GSOC 2024. Please assign me.

**Comment by glaslos** [comment]
@Sam-wiz feel free to give it a try. No assignment needed.
