### ISSUE TITLE
Missing sponsors from the funding page

### ISSUE THREAD

**Issue by dpisano** [honeynet/honeynet.github.io#64]
It looks like we are missing the companies that are sponsoring our work from the funding page. We had this on the old website.

**Comment by glaslos** [comment]
@dpisano do we have a list of sponsors?
Do you think we should add all previous sponsors? I found what we had in the way back machine.

**Comment by dpisano** [comment]
As far as I know the only sponsors right now are DigitalOcean, VMware, and Duo. I don't have a problem of having past sponsors on there.

**Comment by hgascon** [comment]
@glaslos would you add those mentioned by David and the other ones you found to the page? Thanks!

**Comment by glaslos** [comment]
Will send a PR later

**Comment by glaslos** [comment]
https://github.com/honeynet/honeynet.github.io/pull/68
